version: "3.7"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www
    env_file:
      - .env.dev
    ports:
      - "9000:9000"
    networks:
      - local
  nginx:
    image: nginx:latest
    volumes:
      - ./public/:/var/www/public
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5555:80"
    networks:
      - local
    depends_on:
      - webapp
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: app-mysql
    volumes:
      - db-app-data:/var/lib/mysql
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    networks:
      - local
  redis:
    image: redis
    ports:
      - "16379:6379"
    networks:
      - local

volumes:
  db-app-data:

networks:
  local: